sudo: false
dist: trusty
language: generic

cache:
  directories:
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev
      - llvm-5.0-dev
    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal test
